# Generated by Django 4.1.1 on 2022-10-11 08:49


from Location import settings
from django.db import migrations, models

import django.utils.timezone



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    
      
    ]


    operations = [

        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('region', models.CharField(max_length=3)),
                ('profile', models.CharField(max_length=45)),
            ],
        ),
    ]
