# Generated by Django 3.2.16 on 2022-10-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='location',
            name='region',
        ),
        migrations.AddField(
            model_name='location',
            name='age',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='location',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
